#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_BP_MODULES 1
#define CPTCFG_DRM_MODULE 1
#define CPTCFG_DRM_MIPI_DSI 1
#define CPTCFG_DRM_KMS_HELPER_MODULE 1
#define CPTCFG_DRM_KMS_FB_HELPER 1
#define CPTCFG_DRM_FBDEV_EMULATION 1
#define CPTCFG_DRM_FBDEV_OVERALLOC 100
#define CPTCFG_DRM_LOAD_EDID_FIRMWARE 1
#define CPTCFG_DRM_I915_MODULE 1
#define CPTCFG_DRM_I915_FORCE_PROBE ""
#define CPTCFG_DRM_I915_CAPTURE_ERROR 1
#define CPTCFG_DRM_I915_COMPRESS_ERROR 1
#define CPTCFG_DRM_I915_USERPTR 1
#define CPTCFG_DRM_I915_FENCE_TIMEOUT 10000
#define CPTCFG_DRM_I915_USERFAULT_AUTOSUSPEND 250
#define CPTCFG_DRM_I915_HEARTBEAT_INTERVAL 2500
#define CPTCFG_DRM_I915_PREEMPT_TIMEOUT 640
#define CPTCFG_DRM_I915_MAX_REQUEST_BUSYWAIT 8000
#define CPTCFG_DRM_I915_STOP_TIMEOUT 100
#define CPTCFG_DRM_I915_TIMESLICE_DURATION 1
#define CPTCFG_DRM_PANEL 1
#define CPTCFG_DRM_BRIDGE 1
#define CPTCFG_DRM_PANEL_BRIDGE 1
#define CPTCFG_DRM_PANEL_ORIENTATION_QUIRKS_MODULE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
